FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
COPY . ./
RUN dotnet publish Items/ClusterSilo/ClusterSilo.csproj -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /app/out . 
EXPOSE 5000
ENTRYPOINT ["dotnet", "ClusterSilo.dll"]
