interface IChange extends Array<string> { }
interface IChanges extends Array<IChange> { }
interface IRelease extends Array<string | string | IChanges> { 0: string; 1: string; 2: IChanges }
interface IHistory extends Array<IRelease> { }

export class _Changes
{
    static data: IHistory = [
        ['1.1.2', 'xx', [
            ['Add', 'Limit and warning for items on page'],
            ['Add', 'XMPP version response'],
            ['Fix', 'Animation remains even though AnimationsUrl property removed from item'],
        ]],
        ['1.1.1', 'Crafting', [
            ['Add', 'Crafting'],
            ['Add', 'Iframe API library'],
            ['Add', 'Toast when receiving an item'],
            ['Add', 'Popup can adjust height automatically'],
            ['Add', 'Some features for Frank to the iframe API'],
            ['Add', 'Page API'],
            ['Change', 'Default item to quite transparent pyramid to remove visible space used'],
            ['Change', 'Disable items for embedded'],
            ['Fix', 'Item state is not visible remotely'],
            ['Fix', 'Claim certificate not visible remotely'],
            ['Fix', 'Not all signed item properties are sent thru presence, which fails the sig'],
            ['Fix', 'Animated items start animations w/ a hickup'],
            ['Fix', 'Unclosed DIV in chat line'],
        ]],
        ['1.1.0', 'Benji', [
            ['Add', 'Scripting to iframe API & Autorez (Benji, Meerkat)'],
            ['Add', 'Inactive mode (xmpp: presence-show away) and multi-tab presence-show management'],
            ['Add', 'Chat window clear button'],
            ['Add', 'Chat sound controlled by checkbox in chat window (other participants only)'],
            ['Add', 'Initial items'],
            ['Add', 'Effect for miner'],
            ['Change', 'Stay on page if item dropped (which makes Benji a bit unwilling to follow when switching tabs)'],
            ['Change', 'Removed stay-on-tab-change menu entry (there are enough ways to stay)'],
            ['Change', 'Quick slide items without defined avatar speed'],
            ['Change', 'Nickname excluded from copy all text (not selectable)'],
            ['Change', 'Migrate id/nickname/avatar from sync to local storage'],
            ['Change', 'Configure log channels for release version'],
            ['Fix', 'Avatar position resets when dragged while already moving'],
            ['Fix', 'Leave room on any leave from several tabs with the same room'],
            ['Fix', 'Avatars and items flicker when other users navigate'],
        ]],
        ['1.0.9', 'WeblinMigration Web3 RezButton', [
            ['Add', 'transparent iframe'],
            ['Add', 'Document window'],
            ['Add', 'Rez item by button'],
            ['Add', 'Weblin migration'],
            ['Add', 'Label to backpack item'],
            ['Add', 'Web3 based items'],
            ['Add', 'Drop button to backpack item info'],
            ['Add', 'Menu option: send goodbye'],
            ['Change', 'Click through transparent images'],
            ['Change', 'Spawn new item in backpack to free space'],
            ['Fix', 'Accidental backpack item info after drop/pickup from backpack'],
            ['Fix', 'Created items disappear on next presence'],
        ]],
        ['1.0.8', 'Points PrivVidConf Screen Stats', [
            ['Add', 'Greet back'],
            ['Add', 'Chat console opens windows'],
            ['Add', 'Save window state'],
            ['Add', 'Private videoconference'],
            ['Add', 'Activity points'],
            ['Add', 'Item info/stats'],
            ['Add', 'Item shredder'],
            ['Add', 'Chat console /map'],
            ['Add', 'Autostart public viewing on item drop'],
            ['Add', 'Screen item & inter-frame comm'],
        ]],
        ['1.0.7', 'unsafe-eval', [
            ['Add', 'Have items'],
            ['Add', 'Manage page claims'],
            ['Add', 'Detectable for embedded'],
            ['Change', 'Skip call to item config'],
            ['Fix', 'Remove unneccesary unsafe-eval from content_security_policy (for MS Edge Addons Store)'],
        ]],
        ['1.0.6', 'PrivateChat Greet RecvDependentItems', [
            ['Add', 'Allow vidconf fullscreen'],
            ['Add', 'Private chat'],
            ['Add', 'Greet'],
            ['Add', 'Show user dependent items'],
            ['Add', 'Persist stay-on-tab-change flag'],
            ['Add', 'Persist open backpack'],
            ['Add', 'Undock vidconf window'],
            ['Add', 'vpi ignore (e.g. all google)'],
            ['Change', 'RallySpeaker URL variables, iframe allows 4 vidconf'],
            ['Change', 'Much longer chat bubble duration, 2 min. total instead of 20 sec.'],
            ['Change', 'Update to item inventory grain and chat room based inventory view (internal).'],
            ['Fix', 'Chat window focused input style'],
            ['Fix', 'Message replication by tab change'],
        ]],
        ['1.0.5', 'SPA', [
            ['Add', 'Stay in the room if vidconf|inventory|chat are open'],
            ['Change', 'Use new prod cluster'],
            ['Change', 'Preload only idle, move animations'],
            ['Fix', 'No avatar in sleep state without sleep animation'],
            ['Fix', 'Navigate on single page applications (check URL continuously)'],
        ]],
        ['1.0.4', 'Vidconf', [
            ['Add', 'Videoconf demo'],
            ['Add', 'Support for animationsUrl in presence-x-vp:props'],
            ['Add', 'Clickable chat links'],
            ['Add', 'XMPP vCard on hover'],
            ['Add', 'Avatar and item stacking order'],
            ['Change', 'Prefer presence-x-vp:props attributes over identity'],
            ['Change', 'Settings title to brand name (lowercase)'],
            ['Change', 'Variable avatar size'],
            ['Fix', 'Window position on small screens'],
            ['Fix', 'Url mapping (JS undefined)'],
        ]],
        ['1.0.3', 'XmppWindow SettingsDialog', [
            ['Add', 'Change history'],
            ['Add', 'Xmpp console window'],
            ['Add', 'Chat console'],
            ['Add', 'In-screen settings dialog + menu entry'],
            ['Add', 'Support for imageUrl in presence-x-vp:props'],
            ['Add', 'Computed identity digest to presence-x-firebat:...'],
            ['Fix', 'Duplicate presence-x-history'],
            ['Fix', 'Avatar position in presence may be float value instead of int'],
        ]],
        ['1.0.2', 'StoreFix', [
            ['Change', 'VPI query http request to https'],
            ['Add', 'VPI resolver'],
        ]],
        ['1.0.1', 'BackgoundDispatcher', [
            ['Change', 'Backgound room/tab dispatcher'],
        ]],
        ['1.0.0', 'MVP', [
            ['Add', 'Basic function'],
        ]],
    ];
}
